version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python test.py

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: echo "Deploying to the production server"

# workflows:
#   build_test_deploy:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#       - deploy:
#           requires:
#             - test
#           filters:
#             branches:
#               - only: main

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:   # Update the deploy job to a string value
          requires:
            - test
          filters:
            branches:
              only: main   # Update branches to use the correct mapping syntax
